server:
  port: 8082

spring:
  application:
    name: routing-engine
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9093}
    consumer:
      group-id: routing-engine-group
      auto-offset-reset: earliest # Đọc lại từ đầu nếu lỡ mất message
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
