server:
  port: 8083

spring:
  application:
    name: stripe-connector
  threads:
    virtual:
      enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9093}
    template:
      observation-enabled: true
    listener:
      observation-enabled: true
    consumer:
      group-id: stripe-connector-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  resilience4j.circuitbreaker:
    instances:
      stripe: # Tên của cầu dao
        slidingWindowSize: 5 # Đánh giá dựa trên 5 request gần nhất
        failureRateThreshold: 50 # Nếu > 50% bị lỗi (tức 3/5 request) -> NGẮT CẦU DAO
        waitDurationInOpenState: 10s # Ngắt trong 10 giây rồi mới thử mở lại (Half-Open)
        permittedNumberOfCallsInHalfOpenState: 3 # Cho phép thử 3 request để kiểm tra Stripe đã sống lại chưa

stripe:
  api:
    url: ${STRIPE_API_URL:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info # Mở toang cửa cho Prometheus vào đo lường
  tracing:
    sampling:
      probability: 1.0 # Bắt 100% request. (Trên Prod xịn chỉ nên set 0.1 để đỡ tốn ổ cứng)
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans} # Gửi tín hiệu về máy chủ Zipkin
